baseURL = "https://blogs.habsmun.com/"
languageCode = "en-gb"
title = "HabsMUN Blogs"
theme = "newsroom"

[params]
  description = "Official blogs from HABSMUN conferences"
  logo = "/images/habsmunhorizontal2.png"
  faviconsDir = "images/habsmunlogo.png/"

[markup.goldmark.renderer]
  unsafe = true
