baseURL = "https://blogs.habsmun.com/"
languageCode = "en-gb"
title = "HabsMUN Blogs"
theme = ["github.com/onweru/newsroom"]

[params]
  description = "Official blogs from HABSMUN conferences"
  logo = "/images/habsmunhorizontal2.png"

[markup.goldmark.renderer]
  unsafe = true
